### ISSUE TITLE
Does vulcona has a LICENCE?

### ISSUE THREAD

**Issue by avatar-lavventura** [dgarana/vulcano#124]
Is there any `LICENCE` file related to this project or its not created by purpose?

**Comment by dgarana** [comment]
Sorry, forgot to add the LICENSE file. Vulcano is under GNU Genera Public License.

**Comment by avatar-lavventura** [comment]
@dgarana  Thanks. I think, `GNU` and `MIT` is not compatible.

**Comment by avatar-lavventura** [comment]
@dgarana Thanks. I think, `GNU` and `MIT` is not compatible. Is there any chance can you use `GPL` instead of `LGPL`, than there will be no problem.
