### ISSUE TITLE
Add dynamic prompt

### ISSUE THREAD

**Issue by dgarana** [dgarana/vulcano#84]
Would be nice having a dynamic object that could be modified during execution time in order to modify the prompt.

So for example:

>>>
OTHERTHING>>>
OTHERTHING/ANOTHERONE>>>

This could help us to add the profile token on the prompt.

**Comment by dgarana** [comment]
Completed, as now you can pass a function to the prompt

**Comment by marnunez** [comment]
Hi @dgarana ! Where should I pass said function?

**Comment by dgarana** [comment]
Hi @marnunez,
Sorry for the late response.

You can pass that function on the run method of VulcanoAPP.

So, for example:
```
from vulcano.app.classes import VulcanoApp

app = VulcanoApp('my_app')

@app.command
def set_profile(profile_name):
    app.context['profile'] = profile_name


@app.command
def unset_profile():
    app.context['profile'] = profile_name

def _profile_prompt():
    profile = app.context.get('profile')
    prompt_tokens = []
    if profile:
        prompt_tokens.append(
            ('bg:#008800 #ffffff', '[{}]'.format(profile))
        )
    prompt_tokens.append(
        ('', '>> ')
    )
    return prompt_tokens


app.run(prompt=_profile_prompt)
```

Going to open a ticket to create the proper documentation about the dynamic prompt.
